---
- name: Configure AWX
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    awx_organization: "Default"
    git_repo_url: "https://github.com/adborden/ansible-awx.git"

  tasks:
    - name: Create AWX admin token credential
      awx.awx.credential:
        name: "AWX admin"
        organization: "{{ awx_organization }}"
        credential_type: "AWX token"
        inputs:
          awx_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
          awx_token: "{{ lookup('env', 'CONTROLLER_OAUTH_TOKEN') }}"
        state: present

    - name: Create Project
      awx.awx.project:
        name: "awx-configuration"
        organization: "{{ awx_organization }}"
        scm_type: git
        scm_url: "{{ git_repo_url }}"
        scm_branch: feature/awx
        state: present

    - name: Create Inventory
      awx.awx.inventory:
        name: "bayo vista"
        organization: "{{ awx_organization }}"
        state: present

    - name: Create a Job Template with Webhook
      awx.awx.job_template:
        name: "Webhook Demo Job Template"
        project: "awx-configuration"
        inventory: "bayo vista"
        playbook: "hello.yml"
        webhook_service: github
        state: present

    - name: Create ansible-awx job template
      awx.awx.job_template:
        name: "apply awx-configuration"
        project: "awx-configuration"
        inventory: "bayo vista"
        playbook: "site.yaml"
        credentials:
          - AWX admin
        webhook_service: github
        state: present
